[hostname]
ssh_only = false
format = "[$hostname](bold #ff8700) "
disabled = false

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+8'
time_range = '00:00:00-23:00:00'

[git_status]
behind = '⇣${count}'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = '✓'
